# Generated by Django 3.0.8 on 2020-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_videomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onas', models.TextField()),
            ],
        ),
    ]
